defaults: &defaults
  login_ticket:
    lifetime: 600
  service_ticket:
    lifetime_unconsumed: 300
    lifetime_consumed: 86400
  proxy_ticket:
    lifetime_unconsumed: 300
    lifetime_consumed: 86400
  frontend:
    sso_name: "Pbl"
    footer_text: "北京欧亚融信信息技术有限公司"

development:
  <<: *defaults
  authenticators:
    pbl:
      authenticator: "pbl"
      options:

test:
  <<: *defaults
  authenticators:
    static:
      class: "CASino::StaticAuthenticator"
      options:
        users:
          testuser:
            password: "foobar123"

production:
  <<: *defaults
  authenticators:
    pbl:
      authenticator: "pbl"
      options:

staging:
  <<: *defaults
  authenticators:
    pbl:
      authenticator: "pbl"
      options:
