default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: pbl_sso_development

test:
  <<: *default
  database: pbl_sso_test

production:
  <<: *default
  database: pbl_sso_production
  username: pbl
  password: pbl

staging:
  <<: *default
  database: pbl_sso_staging
  username: pbl
  password: pbl

release:
  <<: *default
  database: pbl_sso_release
  username: pbl
  password: pbl

